services:
  db_qr_test:
    container_name: ms-qr-test
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qr_postgres
